server:
  port: 8989

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: service-zipkin2
  zipkin:
    base-url: http://localhost:9411
