eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    service-ribbon:
      path: /service-ribbon/**
      serviceId: service-ribbon
    service-feign:
      path: /service-feign/**
      serviceId: service-feign


